project:
  type: default
  render:
    - index.qmd

format:
  pdf:
    documentclass: memoir
    classoption: [11pt, a4paper, openany]
    include-in-header:
      text: |
        \usepackage[english, samf]{ku-frontpage}
        \assignment{Seminar paper}
        \advisor{Advisor: Jacob Lundbeck Serup}
        \let\frontmatter\relax
        \let\mainmatter\relax
        \let\backmatter\relax
    number-sections: true
    colorlinks: true
    geometry:
      - top=20mm
      - left=20mm
      - bottom=20mm
      - right=20mm
    bibliography: references.bib
    cite-method: natbib
    biblio-style: apalike
    lang: en
    fontsize: 12pt
    highlight-style: github-light

execute:
  echo: false
  warning: false

jupyter: python3