<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-dark-23bbe8b5e4efc1e257f6d59dce478b08.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Tobias Dines Schlünssen (GFS189)">
  <meta name="author" content="Conrad Frederik Kromann (RTL959)">
  <meta name="dcterms.date" content="2026-06-02">
  <title>Betting Against Beta</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-e591a9bd7cd3ecb4fbafa5d10a11e8b1.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Betting Against Beta</h1>
  <p class="subtitle">Testing Proposition 1 &amp; 2 in American Equity Markets</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Tobias Dines Schlünssen (GFS189) 
</div>
        <p class="quarto-title-affiliation">
            Department of Economics · University of Copenhagen
          </p>
    </div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Conrad Frederik Kromann (RTL959) 
</div>
</div>
</div>

  <p class="date">2026-06-02</p>
</section>
<section>
<section id="agenda" class="title-slide slide level1 section-slide center" data-background="linear-gradient(135deg, #A31D20 0%, #6e1215 100%)">
<h1>Agenda</h1>

</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<ul class="agenda-list">
<li>
Motivation &amp; Research Question
</li>
<li>
Theoretical Framework — CAPM &amp; Leverage Constraints
</li>
<li>
Propositions 1 &amp; 2 (Frazzini &amp; Pedersen, 2014)
</li>
<li>
Data &amp; Methodology
</li>
<li>
Results — Proposition 1: The Security Market Line
</li>
<li>
Results — Proposition 2: BAB Factor Performance
</li>
<li>
Results — Transaction Costs
</li>
<li>
Discussion &amp; Conclusion
</li>
</ul>
</section></section>
<section>
<section id="motivation" class="title-slide slide level1 section-slide center" data-background="linear-gradient(135deg, #A31D20 0%, #6e1215 100%)">
<h1>Motivation</h1>

</section>
<section id="the-beta-anomaly" class="slide level2">
<h2>The Beta Anomaly</h2>
<div class="columns-custom">
<div>
<p><strong>CAPM Prediction</strong></p>
<p>The Capital Asset Pricing Model predicts a <em>positive, linear</em> relationship between beta and expected return:</p>
<p><span class="math display">\[R_i - r_f = \alpha + \beta(R_m - r_f) + \varepsilon\]</span></p>
<ul>
<li>Higher <span class="math inline">\(\beta\)</span> → higher expected return</li>
<li>All assets lie on the <strong>Security Market Line (SML)</strong></li>
<li><span class="math inline">\(\alpha = 0\)</span> for all assets in equilibrium</li>
</ul>
</div>
<div>
<p><strong>The Empirical Reality</strong></p>
<div class="highlight-box">
<p>High-beta stocks tend to have <strong>lower</strong> alphas than their CAPM-predicted values — contradicting the model.</p>
</div>
<p>This is the <strong>beta anomaly</strong>: the empirical SML is significantly <em>flatter</em> than CAPM predicts.</p>
<p>Evidence: <span class="citation" data-cites="blackjensenscholes1972">Black et al. (<a href="#/references" role="doc-biblioref" onclick="">1972</a>)</span>, <span class="citation" data-cites="famafrench1992">Fama and French (<a href="#/references" role="doc-biblioref" onclick="">1992</a>)</span>, <span class="citation" data-cites="famafrench2004">Fama and French (<a href="#/references" role="doc-biblioref" onclick="">2004</a>)</span></p>
</div>
</div>
</section>
<section id="research-question" class="slide level2">
<h2>Research Question</h2>
<div class="finding-box">
<p><strong>We test two propositions from <span class="citation" data-cites="frazzinipedersen2014">Frazzini and Pedersen (<a href="#/references" role="doc-biblioref" onclick="">2014</a>)</span>:</strong></p>
<ol type="1">
<li>Is there a negative relationship between beta and alpha? <em>(Proposition 1)</em></li>
<li>Does a long–short BAB strategy exploiting this anomaly generate positive returns? <em>(Proposition 2)</em></li>
</ol>
</div>
<p><strong>Sample:</strong> US equities, January 1963 – December 2025</p>
<p><strong>Extension:</strong> We introduce <strong>transaction costs</strong> to assess whether the strategy survives real-world trading frictions.</p>
</section></section>
<section>
<section id="theoretical-framework" class="title-slide slide level1 section-slide center" data-background="linear-gradient(135deg, #A31D20 0%, #6e1215 100%)">
<h1>Theoretical Framework</h1>

</section>
<section id="why-does-the-beta-anomaly-exist" class="slide level2">
<h2>Why Does the Beta Anomaly Exist?</h2>
<div class="columns-custom">
<div>
<p><strong>Leverage Constraints</strong></p>
<p>When investors <em>cannot borrow freely</em>, they compensate by over-buying high-beta risky assets.</p>
<ul>
<li>Excess demand → <strong>lower expected returns</strong> for high-beta assets</li>
<li>The SML becomes <strong>flatter</strong> than CAPM predicts</li>
<li>High-beta assets become <em>overpriced</em>; low-beta assets <em>underpriced</em></li>
</ul>
</div>
<div>
<p><strong>Equilibrium Expected Return</strong></p>
<p><span class="citation" data-cites="frazzinipedersen2014">Frazzini and Pedersen (<a href="#/references" role="doc-biblioref" onclick="">2014</a>)</span> show:</p>
<p><span class="math display">\[E_t(r^s_{t+1}) = r^f + \psi_t + \beta^s_t \lambda_t\]</span></p>
<p>where <span class="math inline">\(\psi_t\)</span> measures the <strong>tightness of funding constraints</strong> and <span class="math inline">\(\lambda_t\)</span> is the risk premium adjusted for these constraints.</p>
<p>A security’s CAPM alpha then equals:</p>
<p><span class="math display">\[\alpha^s_t = \psi_t(1 - \beta^s_t)\]</span></p>
</div>
</div>
</section>
<section id="proposition-1-high-beta-is-low-alpha" class="slide level2">
<h2>Proposition 1: High Beta is Low Alpha</h2>
<p><span class="math display">\[\alpha^s_t = \psi_t\,(1 - \beta^s_t)\]</span></p>
<div class="columns-custom">
<div>
<p><strong>Implications:</strong></p>
<ul>
<li><span class="math inline">\(\alpha^s\)</span> is <em>decreasing</em> in <span class="math inline">\(\beta^s\)</span></li>
<li>When <span class="math inline">\(\beta^s &gt; 1\)</span>: <span class="math inline">\(\alpha &lt; 0\)</span> → <strong>high-beta stocks are overpriced</strong></li>
<li>When <span class="math inline">\(\beta^s &lt; 1\)</span>: <span class="math inline">\(\alpha &gt; 0\)</span> → <strong>low-beta stocks are underpriced</strong></li>
<li>The Sharpe ratio is highest for <span class="math inline">\(\beta &lt; 1\)</span></li>
</ul>
</div>
<div>
<div class="highlight-box">
<p><strong>Testable prediction:</strong> Running Fama–MacBeth cross-sectional regressions of excess returns on beta should yield a slope that is <em>significantly below</em> the average market excess return, ideally indistinguishable from zero.</p>
</div>
</div>
</div>
</section>
<section id="proposition-2-the-bab-factor" class="slide level2">
<h2>Proposition 2: The BAB Factor</h2>
<p>Let <span class="math inline">\(w^L_t\)</span> be weights on low-beta stocks (return <span class="math inline">\(r^L\)</span>) and <span class="math inline">\(w^H_t\)</span> on high-beta stocks (return <span class="math inline">\(r^H\)</span>):</p>
<p><span class="math display">\[r^{BAB}_{t+1} = \frac{1}{\beta^L_t}(r^L_{t+1} - r^f) - \frac{1}{\beta^H_t}(r^H_{t+1} - r^f)\]</span></p>
<div class="columns-60-40">
<div>
<p><strong>Strategy mechanics:</strong></p>
<ul>
<li><strong>Long</strong> leg: leveraged low-beta portfolio (scaled to <span class="math inline">\(\beta = 1\)</span>)</li>
<li><strong>Short</strong> leg: de-leveraged high-beta portfolio (scaled to <span class="math inline">\(\beta = 1\)</span>)</li>
<li>The combined portfolio is <strong>market-neutral</strong> (<span class="math inline">\(\beta = 0\)</span>)</li>
</ul>
</div>
<div>
<div class="result-box">
<p><strong>Expected return:</strong> <span class="math display">\[E_t(r^{BAB}) = \frac{\beta^H_t - \beta^L_t}{\beta^L_t \beta^H_t}\,\psi_t \geq 0\]</span></p>
<p>Increasing in the beta spread and funding constraint tightness <span class="math inline">\(\psi_t\)</span>.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="data-methodology" class="title-slide slide level1 section-slide center" data-background="linear-gradient(135deg, #A31D20 0%, #6e1215 100%)">
<h1>Data &amp; Methodology</h1>

</section>
<section id="data" class="slide level2">
<h2>Data</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Dataset</th>
<th>Frequency</th>
<th>Content</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CRSP stock data</td>
<td>Monthly</td>
<td>Excess returns, market cap</td>
<td>BAB portfolio &amp; factor returns</td>
</tr>
<tr class="even">
<td>CRSP stock data</td>
<td>Daily</td>
<td>Excess returns, bid-ask</td>
<td>Volatility (β); transaction costs</td>
</tr>
<tr class="odd">
<td>Fama-French factors</td>
<td>Monthly &amp; Daily</td>
<td>Risk-free rate, market excess return</td>
<td>Excess returns; correlation (β)</td>
</tr>
</tbody>
</table>
<p><strong>Sample:</strong> January 1963 – December 2025 · NYSE, AMEX, NASDAQ</p>
<div class="caption">
<p>Data accessed via the <code>tidyfinance</code> Python package through WRDS; Fama-French data from Kenneth French Data Library.</p>
</div>
</section>
<section id="beta-estimation" class="slide level2">
<h2>Beta Estimation</h2>
<p>Following <span class="citation" data-cites="frazzinipedersen2014">Frazzini and Pedersen (<a href="#/references" role="doc-biblioref" onclick="">2014</a>)</span>, beta is estimated in <strong>two components</strong>:</p>
<div class="columns-custom">
<div>
<p><strong>Volatility</strong> (daily returns, 1-year rolling): <span class="math display">\[\hat{\sigma}_i = \text{std}(\text{daily } r_i), \quad \hat{\sigma}_m = \text{std}(\text{daily } r_m)\]</span></p>
<p><strong>Correlation</strong> (monthly returns, 5-year rolling): <span class="math display">\[\hat{\rho}_{im} = \text{corr}(\text{monthly } r_i,\; r_m)\]</span></p>
<p><strong>Combined estimate:</strong> <span class="math display">\[\hat{\beta}_i = \hat{\rho}_{im} \cdot \frac{\hat{\sigma}_i}{\hat{\sigma}_m}\]</span></p>
</div>
<div>
<div class="highlight-box">
<p><strong>Vasicek shrinkage</strong> — shrink each time-series beta toward the cross-sectional mean:</p>
<p><span class="math display">\[\hat{\beta}^{shrunk}_i = 0.6\;\hat{\beta}_i + 0.4 \times 1\]</span></p>
<p>This reduces estimation error for stocks with short histories.</p>
</div>
</div>
</div>
</section>
<section id="bab-factor-construction" class="slide level2">
<h2>BAB Factor Construction</h2>
<div class="columns-custom">
<div>
<p><strong>Each month:</strong></p>
<ol type="1">
<li>Sort stocks by <span class="math inline">\(\hat{\beta}^{shrunk}\)</span> into <strong>above-</strong> and <strong>below-median</strong> halves</li>
<li>Assign <strong>rank weights</strong> within each half — more extreme betas receive more weight (lowest-beta stocks dominate the long leg; highest-beta stocks dominate the short leg)</li>
<li>Compute leg betas <span class="math inline">\(\hat{\beta}^L\)</span>, <span class="math inline">\(\hat{\beta}^H\)</span></li>
<li>Scale both legs to unit beta and compute BAB return</li>
</ol>
</div>
<div>
<p><strong>Testing Proposition 1 — Fama-MacBeth:</strong></p>
<p>Each month estimate: <span class="math display">\[r^{excess}_{i,t} = \gamma_0 + \gamma_1 \hat{\beta}_{i,t-1} + \varepsilon_{i,t}\]</span></p>
<p>Time-series average <span class="math inline">\(\bar{\gamma}_1\)</span> should be <strong>near zero</strong> (anomaly present) vs.&nbsp;CAPM prediction of <span class="math inline">\(\bar{\gamma}_1 \approx \bar{r}^{excess}_m\)</span>.</p>
<p>Also compute CAPM <span class="math inline">\(\alpha\)</span> for each <strong>beta-sorted decile portfolio</strong>.</p>
</div>
</div>
</section></section>
<section>
<section id="results" class="title-slide slide level1 section-slide center" data-background="linear-gradient(135deg, #A31D20 0%, #6e1215 100%)">
<h1>Results</h1>

</section>
<section id="proposition-1-fama-macbeth-results" class="slide level2">
<h2>Proposition 1: Fama-MacBeth Results</h2>
<div class="columns-custom">
<div>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Mean (%/month)</th>
<th style="text-align: right;"><em>t</em>-statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td style="text-align: right;"><strong>0.79</strong></td>
<td style="text-align: right;">5.89</td>
</tr>
<tr class="even">
<td>Beta</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.75</td>
</tr>
</tbody>
</table>
<div class="caption">
<p>Time-series averages of monthly cross-sectional Fama-MacBeth coefficients. <em>t</em>-stats from time-series standard error.</p>
</div>
</div>
<div>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Intercept of <span class="key-stat">0.79%/month</span> is highly significant</li>
<li>Beta slope <span class="key-stat">0.14%/month</span> is <em>indistinguishable from zero</em> (<em>t</em> = 0.75)</li>
<li>CAPM predicts slope ≈ average market excess return (≫ 0.14%)</li>
</ul>
<div class="result-box">
<p><strong>→ Supports Proposition 1:</strong> The empirical compensation for bearing systematic risk is far below what CAPM predicts.</p>
</div>
</div>
</div>
</section>
<section id="proposition-1-security-market-line" class="slide level2">
<h2>Proposition 1: Security Market Line</h2>
<div class="columns-custom">
<div>
<p><strong>Beta-decile SML vs.&nbsp;CAPM prediction</strong></p>
<ul>
<li>Empirical SML (blue) is significantly <em>flatter</em> than the CAPM line (red dashed)</li>
<li>The extreme high-beta decile (avg <span class="math inline">\(\hat{\beta} \approx 2.1\)</span>) earns clearly <em>below</em> its CAPM-predicted return</li>
</ul>
<div class="highlight-box">
<p><strong>Apparent tension:</strong> The FMB slope (0.14%) is slightly <em>positive</em>, yet the decile SML appears to slope <em>downward</em>. Both are consistent with the anomaly — Fama-MacBeth weights all stocks equally so moderate-beta stocks dominate the slope, while the decile plot gives the extreme high-beta group disproportionate leverage on the fitted line.</p>
</div>
</div>
<div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../figures/sml.png" style="width:100.0%"></p>
<figcaption>Empirical SML vs CAPM</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="proposition-1-decile-alpha-results" class="slide level2">
<h2>Proposition 1: Decile Alpha Results</h2>
<div class="columns-custom">
<div>
<p><strong>Broadly declining alpha across deciles:</strong></p>
<ul>
<li><strong>Decile 1</strong> (avg <span class="math inline">\(\beta = 0.49\)</span>): <span class="math inline">\(\alpha = +0.27\%\)</span>/month (significant)</li>
<li><strong>Decile 2</strong>: <span class="math inline">\(\alpha = +0.22\%\)</span>/month, <span class="math inline">\(t &gt; 2.4\)</span></li>
<li><strong>Decile 3</strong>: <span class="math inline">\(\alpha = +0.25\%\)</span>/month, <span class="math inline">\(t &gt; 3.2\)</span></li>
<li><strong>Decile 6</strong> (avg <span class="math inline">\(\beta \approx 1.0\)</span>): <span class="math inline">\(\alpha \approx 0\%\)</span></li>
<li><strong>Decile 10</strong> (avg <span class="math inline">\(\beta = 2.10\)</span>): <span class="math inline">\(\alpha = -0.82\%\)</span>/month, <span class="math inline">\(t = -3.16\)</span></li>
</ul>
<div class="result-box">
<p>Alpha spread (decile 1 → 10): approximately <strong>−1.1 pp/month</strong> — the pattern is monotone and statistically significant across multiple deciles, not just at the extremes.</p>
</div>
</div>
<div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../figures/decile_alphas.png" style="width:100.0%"></p>
<figcaption>CAPM alpha by beta decile</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="proposition-2-bab-factor-performance" class="slide level2">
<h2>Proposition 2: BAB Factor Performance</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">BAB Factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ann. Mean Return</td>
<td style="text-align: right;"><strong>8.85%</strong></td>
</tr>
<tr class="even">
<td>Ann. Std. Deviation</td>
<td style="text-align: right;">11.26%</td>
</tr>
<tr class="odd">
<td>Sharpe Ratio</td>
<td style="text-align: right;"><strong>0.79</strong></td>
</tr>
<tr class="even">
<td><em>t</em>-statistic</td>
<td style="text-align: right;"><strong>6.08</strong></td>
</tr>
</tbody>
</table>
<div class="caption">
<p>Performance statistics for the BAB factor following <span class="citation" data-cites="frazzinipedersen2014">Frazzini and Pedersen (<a href="#/references" role="doc-biblioref" onclick="">2014</a>)</span>. Mean and SD annualised (×12, ×√12). Sample: US equities, January 1963 – December 2025.</p>
</div>
<div class="result-box">
<p><strong>Sharpe ratio of 0.79</strong> with <em>t</em>-stat of <strong>6.08</strong> — strongly statistically significant positive returns. <strong>→ Supports Proposition 2.</strong></p>
</div>
</section>
<section id="bab-cumulative-return" class="slide level2">
<h2>BAB Cumulative Return</h2>
<div class="columns-60-40">
<div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../figures/bab_cumret.png" style="width:100.0%"></p>
<figcaption>Cumulative BAB return ($1 invested at inception)</figcaption>
</figure>
</div>
</div>
<div>
<p><strong>Key observations:</strong></p>
<ul>
<li>Strong growth through the <strong>1990s</strong></li>
<li>Partial retrace during <strong>2000–2010</strong></li>
<li>Recovery and further compounding toward <strong>2025</strong></li>
</ul>
<p>The strategy generates meaningful returns over the full sample, with considerable sub-period variation.</p>
</div>
</div>
</section>
<section id="transaction-costs" class="slide level2">
<h2>Transaction Costs</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Gross BAB</th>
<th style="text-align: right;">Net BAB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ann. Mean Return</td>
<td style="text-align: right;"><strong>9.18%</strong></td>
<td style="text-align: right;"><strong>−51.12%</strong></td>
</tr>
<tr class="even">
<td><em>t</em>-statistic</td>
<td style="text-align: right;">3.94</td>
<td style="text-align: right;">−13.98</td>
</tr>
<tr class="odd">
<td>Avg. Annual TC Drag</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>60.30 pp</strong></td>
</tr>
</tbody>
</table>
<div class="caption">
<p>TC subsample: January 1993 – December 2025 (start date driven by CRSP bid-ask spread data availability). Round-trip costs from CRSP daily bid-ask half-spreads, assuming full monthly rebalancing.</p>
</div>
<div class="highlight-box">
<p><strong>The TC drag of 60.30 pp/year far exceeds the gross return of 8.85%.</strong> Under full monthly rebalancing the strategy is entirely non-viable after realistic trading frictions.</p>
</div>
</section></section>
<section>
<section id="discussion" class="title-slide slide level1 section-slide center" data-background="linear-gradient(135deg, #A31D20 0%, #6e1215 100%)">
<h1>Discussion</h1>

</section>
<section id="proposition-1-in-context" class="slide level2">
<h2>Proposition 1 in Context</h2>
<div class="columns-custom">
<div>
<p><strong>Consistent with prior literature:</strong></p>
<ul>
<li><span class="citation" data-cites="blackjensenscholes1972">Black et al. (<a href="#/references" role="doc-biblioref" onclick="">1972</a>)</span> — first systematic evidence of flat SML (NYSE, 1926–1966)</li>
<li><span class="citation" data-cites="famafrench1992">Fama and French (<a href="#/references" role="doc-biblioref" onclick="">1992</a>)</span> — beta loses explanatory power once size &amp; book-to-market included</li>
<li><span class="citation" data-cites="famafrench2004">Fama and French (<a href="#/references" role="doc-biblioref" onclick="">2004</a>)</span> — CAPM core prediction contradicted by data</li>
</ul>
<p>Our results <strong>replicate</strong> the core finding of <span class="citation" data-cites="frazzinipedersen2014">Frazzini and Pedersen (<a href="#/references" role="doc-biblioref" onclick="">2014</a>)</span> on an extended US sample (1963–2025).</p>
</div>
<div>
<div class="finding-box">
<p><strong>Our estimates:</strong></p>
<ul>
<li>FMB beta slope: 0.14%/month (<em>t</em> = 0.75) — near zero</li>
<li>Alpha spread (decile 1 to 10): ≈ −1.1 pp/month</li>
<li>Both economically large and statistically significant at the distribution extremes</li>
</ul>
<p>Extends <span class="citation" data-cites="frazzinipedersen2014">Frazzini and Pedersen (<a href="#/references" role="doc-biblioref" onclick="">2014</a>)</span>’s sample period by ~13 years with consistent conclusions.</p>
</div>
</div>
</div>
</section>
<section id="proposition-2-in-context" class="slide level2">
<h2>Proposition 2 in Context</h2>
<div class="columns-custom">
<div>
<p><strong>No post-publication decay:</strong></p>
<ul>
<li>Gross BAB in TC subsample (1993–2025): <strong>9.18%</strong> (<em>t</em> = 3.94)</li>
<li>Full sample (1963–2025): <strong>8.85%</strong> (<em>t</em> = 6.08)</li>
<li>The anomaly appears <strong>persistent</strong> into the more recent period</li>
</ul>
<p><span class="citation" data-cites="bakerbradleywurgler2011">Baker et al. (<a href="#/references" role="doc-biblioref" onclick="">2011</a>)</span> predict decay as capital flows to exploit the anomaly — our data do <strong>not</strong> strongly support this narrative.</p>
</div>
<div>
<p><strong>Transaction costs are overstated:</strong></p>
<p>Our TC estimate is an <em>extreme upper bound</em>. <span class="citation" data-cites="frazziniisraelmoskowitz2015">Frazzini et al. (<a href="#/references" role="doc-biblioref" onclick="">2015</a>)</span> use proprietary execution data and find effective implementation costs of <strong>tens of basis points</strong> per year — the strategy remains profitable after realistic costs.</p>
<div class="highlight-box">
<p>Our TC result is best read as a <strong>sensitivity analysis</strong>, not a verdict on strategy viability.</p>
</div>
</div>
</div>
</section>
<section id="limitations" class="slide level2">
<h2>Limitations</h2>
<div class="columns-custom">
<div>
<p><strong>Sample scope:</strong></p>
<ul>
<li>US equities only</li>
<li><span class="citation" data-cites="frazzinipedersen2014">Frazzini and Pedersen (<a href="#/references" role="doc-biblioref" onclick="">2014</a>)</span> document BAB profitability in <strong>20 international markets</strong> and multiple asset classes</li>
</ul>
<p><strong>TC methodology:</strong></p>
<ul>
<li>CRSP quoted spreads are wide pre-2001 (⅛ dollar tick)</li>
<li>Full monthly rebalancing → upper bound on turnover</li>
<li>Effective spreads ≈ ½ of quoted spreads for large institutions</li>
</ul>
</div>
<div>
<p><strong>Construction &amp; bias:</strong></p>
<ul>
<li>High-beta stocks more likely to be small, volatile, distressed</li>
<li>Delisting return corrections could affect top-decile alpha estimates</li>
</ul>
<p><strong>Sub-period analysis:</strong></p>
<ul>
<li>No split by pre/post-decimalization (2001)</li>
<li>Growing institutional awareness of BAB post-2014</li>
</ul>
</div>
</div>
</section></section>
<section>
<section id="conclusion" class="title-slide slide level1 section-slide center" data-background="linear-gradient(135deg, #A31D20 0%, #6e1215 100%)">
<h1>Conclusion</h1>

</section>
<section id="key-findings" class="slide level2">
<h2>Key Findings</h2>
<div class="columns-custom">
<div>
<p><strong>Proposition 1 ✓</strong></p>
<div class="result-box">
<p>Strong evidence of a <strong>negative beta–alpha relationship</strong> in US equities (1963–2025).</p>
<p>FMB beta slope: 0.14%/month (<em>t</em> = 0.75) — far below the CAPM prediction.</p>
<p>Alpha spread across deciles: ≈ −1.1 pp/month.</p>
</div>
<p><strong>Proposition 2 ✓</strong></p>
<div class="result-box">
<p>BAB factor earns <strong>8.85% annualised</strong> (SR = 0.79, <em>t</em> = 6.08) — strongly supporting positive expected returns from the strategy.</p>
</div>
</div>
<div>
<p><strong>Transaction Costs ⚠</strong></p>
<div class="highlight-box">
<p>Under full monthly rebalancing with CRSP quoted spreads, TC drag of <strong>60.30 pp/year</strong> renders the net BAB return <strong>−51.12%</strong>.</p>
<p>This is an <em>upper bound</em> — realistic implementation costs would be substantially lower <span class="citation" data-cites="frazziniisraelmoskowitz2015">(<a href="#/references" role="doc-biblioref" onclick="">Frazzini et al. 2015</a>)</span>.</p>
</div>
<p><strong>Future Research</strong></p>
<ul>
<li>International replication</li>
<li>Effective spread estimates &amp; post-decimalization costs</li>
<li>Sub-period analysis (pre/post 2001)</li>
<li>Delisting return corrections</li>
</ul>
</div>
</div>
</section>
<section id="section" class="slide level2 center" data-background="linear-gradient(135deg, #1a1a2e 0%, #0f3460 60%, #A31D20 100%)">
<h2></h2>
<div style="text-align: center; padding: 3rem;">
<h1 style="font-size: 2.8em; color: white; border: none; margin-bottom: 0.5rem;">
Questions?
</h1>
<p style="font-size: 1.1em; color: #c8d8e8; margin-bottom: 2.5rem;">
We welcome comments and discussion
</p>
<hr style="border-color: rgba(255,255,255,0.3); width: 40%; margin: 1rem auto 2rem auto;">
<p style="font-size: 0.85em; color: #9bb0c9;">
<strong>Tobias Dines Schlünssen</strong> · GFS189<br> <strong>Conrad Frederik Kromann</strong> · RTL959<br><br> Department of Economics · University of Copenhagen<br> Seminar: Asset Prices and Financial Markets · June 2026
</p>
<p>:::</p>
<section id="references" class="slide level2 smaller scrollable">
<h2>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-bakerbradleywurgler2011" class="csl-entry" role="listitem">
Baker, Malcolm, Brendan Bradley, and Jeffrey Wurgler. 2011. <span>“Benchmarks as Limits to Arbitrage: Understanding the Low-Volatility Anomaly.”</span> <em>Financial Analysts Journal</em> 67 (1): 40–54. <a href="https://doi.org/10.2469/faj.v67.n1.4">https://doi.org/10.2469/faj.v67.n1.4</a>.
</div>
<div id="ref-blackjensenscholes1972" class="csl-entry" role="listitem">
Black, Fischer, Michael C. Jensen, and Myron Scholes. 1972. <span>“The Capital Asset Pricing Model: Some Empirical Tests.”</span> In <em>Studies in the Theory of Capital Markets</em>, edited by Michael C. Jensen. Praeger.
</div>
<div id="ref-famafrench1992" class="csl-entry" role="listitem">
Fama, Eugene F., and Kenneth R. French. 1992. <span>“The Cross-Section of Expected Stock Returns.”</span> <em>Journal of Finance</em> 47 (2): 427–65. <a href="https://doi.org/10.1111/j.1540-6261.1992.tb04398.x">https://doi.org/10.1111/j.1540-6261.1992.tb04398.x</a>.
</div>
<div id="ref-famafrench2004" class="csl-entry" role="listitem">
Fama, Eugene F., and Kenneth R. French. 2004. <span>“The Capital Asset Pricing Model: Theory and Evidence.”</span> <em>Journal of Economic Perspectives</em> 18 (3): 25–46. <a href="https://doi.org/10.1257/0895330042162430">https://doi.org/10.1257/0895330042162430</a>.
</div>
<div id="ref-frazziniisraelmoskowitz2015" class="csl-entry" role="listitem">
Frazzini, Andrea, Ronen Israel, and Tobias J. Moskowitz. 2015. <span>“Trading Costs of Asset Pricing Anomalies.”</span> <em>Fama-Miller Working Paper</em>.
</div>
<div id="ref-frazzinipedersen2014" class="csl-entry" role="listitem">
Frazzini, Andrea, and Lasse Heje Pedersen. 2014. <span>“Betting Against Beta.”</span> <em>Journal of Financial Economics</em> 111 (1): 1–25. https://doi.org/<a href="https://doi.org/10.1016/j.jfineco.2013.10.005">https://doi.org/10.1016/j.jfineco.2013.10.005</a>.
</div>
</div>

</section>
</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: false,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>