# Introduction
One of the central prediction of the capital asset priciing model(CAPM) is the linear relationship bewtween expected returns and systemtic risk which is undiversifable. This relationship however has long been challenged by empircal evidence which suggest a much flatter line than prediced by the model. A reason for this, suggested by the literature such as Fama and French (2004) [@famafrench2004], is the presence of the market anomalies suchs as high-beta assets yielding lower retruns compared to lower beta assets completly contradicting the model expectations. This is called the beta anomomly and a way of explaoitng this anomoly the investing strategy of betting against beta (BAB).

Introduced by Frazzini and Pedersen (2014) [@frazzinipedersen2014] the BAB-strategy is a simple long-short strategy which exploits the beta anomaly by going long on low beta stocks and short on high beta stocks. The strategy has been shown to generate positive returns when varying the markets and time-periods making it an attractive investment strategy for investors looking to capitalize on the beta anomaly. However, the performance of the BAB-strategy is not without controversy, with some studies suggesting that the strategy may not be as effective as initially thought, and that its performance may be driven by other factors such as size and value effects which is also documented by Frazzini and Pedersen (2014) [@frazzinipedersen2014]. 


To examine the relevance of the beta anomaly we test the propositions 1 and 2 from the paper of Frazzini and Pedersen (2014) [@frazzinipedersen2014] . The first proposition states that there is a negative relationship between beta and alpha, which implies that stocks with higher betas tend to have lower alphas than those with lower betas. The second proposition states that a strategy which exploits this market anomaly by going long on low beta stocks and short on high beta stocks, known as the BAB-portfolio, should generate positive returns.

For best understanding and comprehension of the subject mattter the paper structure is as follows: first, we introduce the theoretical background and framwork for the CAPM and the why the existence of the beta anomaly is possible according to existing literature. Second, we describe our data and methodology for testing the anomoly and the performance of the BAB-strategy and how we introduce transaction-costs as an extension of the analasys of Frazzini and Pedersen (2014) [@frazzinipedersen2014]. This is equivalent to testing proposition 1 and 2. Third, we present the results. fourth, we connect our results to the existing litearture and the implications. Lastly, we conclude and suggest avenues for future research.

Using US equaity data for the period 1990-2020 we find that a negative relationship between beta and alpha, which supports proposition 1 and that the beta-anomoly is present leading to a flatter market security line. We also find that the BAB-portfolio generates positive returns, which supports proposition 2. However, when we introduce transaction costs into our analysis, we find that the performance of the BAB-portfolio is significantly reduced, suggesting that the strategy may not be as effective as initially thought when accounting for real-world trading frictions.
\
